name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting up environment
      run: ./require.sh
    - name: create lib
      run: make lib
    - name: create tests
      run: make tests
    - name: execute main tests
      run: make run_main_tests
    - name: execute unit tests
      run: make run_unit_tests
